### ISSUE TITLE
SQL Injection - Unfiltered Input Data Into SQL

### ISSUE THREAD

**Issue by Ciordelice** [a-c-technologies/AC.T#1]
https://github.com/a-c-technologies/AC.T/blob/5456e6364b9a33f80beaf8e73f1239c9fac09a41/index.php#L200

**Comment by a-c-technologies** [comment]
Hi ! Yep i know i am not at security step yet ... if you have time to secure it and want to help ... you can start securing it

**Comment by a-c-technologies** [comment]
Bug fixed redownload/clone forom master to check
